package storageusecase

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"time"

	infra "air_orchestrator/internal/infrastructure/storage"

	"github.com/google/uuid"
)

const defaultPresignedURLTTL = 24 * time.Hour

type File struct {
	Key         string
	FileName    string
	Size        int64
	ContentType string
	ModifiedAt  time.Time
	URL         string
}

type Service struct {
	resolver infra.StorageResolver
}

func NewService(resolver infra.StorageResolver) *Service {
	return &Service{resolver: resolver}
}

func (s *Service) CreateTextFile(ctx context.Context, userID uint32, name string, content io.Reader, size int64) (*File, error) {
	return s.put(ctx, userID, name, content, size, "text/plain; charset=utf-8")
}

func (s *Service) SaveImage(ctx context.Context, userID uint32, name string, content io.Reader, size int64, contentType string) (*File, error) {
	if contentType == "" {
		contentType = "application/octet-stream"
	}
	return s.put(ctx, userID, name, content, size, contentType)
}

func (s *Service) ListFiles(ctx context.Context, userID uint32) ([]File, error) {
	storage, err := s.resolve(ctx, userID)
	if err != nil {
		return nil, err
	}
	result, err := storage.ListObjects(ctx, userPrefix(userID), infra.ListOptions{})
	if err != nil {
		return nil, err
	}
	files := make([]File, 0, len(result.Objects))
	for _, object := range result.Objects {
		if err := validateUserKey(userID, object.Key); err != nil {
			return nil, fmt.Errorf("storage returned invalid object key: %w", err)
		}
		name := filepath.Base(object.Key)
		// Keys generated by put use a UUID (36 chars) followed by '-'.
		// Splitting at the first hyphen is incorrect because UUIDs contain hyphens.
		if len(name) > 37 && name[36] == '-' {
			name = name[37:]
		}
		url, err := storage.PresignedGetURL(ctx, object.Key, defaultPresignedURLTTL)
		if err != nil {
			return nil, err
		}
		files = append(files, File{Key: object.Key, FileName: name, Size: object.Size, ModifiedAt: object.LastModified, URL: url})
	}
	return files, nil
}

func (s *Service) DeleteFile(ctx context.Context, userID uint32, key string) error {
	if err := validateUserKey(userID, key); err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if strings.TrimSpace(key) == userPrefix(userID) {
		return fmt.Errorf("object does not belong to user")
	}
	storage, err := s.resolve(ctx, userID)
	if err != nil {
		return err
	}
	return storage.DeleteObject(ctx, key)
}

func (s *Service) DeleteAll(ctx context.Context, userID uint32) error {
	storage, err := s.resolve(ctx, userID)
	if err != nil {
		return err
	}
	result, err := storage.ListObjects(ctx, userPrefix(userID), infra.ListOptions{})
	if err != nil {
		return err
	}
	for _, object := range result.Objects {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := validateUserKey(userID, object.Key); err != nil {
			return fmt.Errorf("storage returned invalid object key: %w", err)
		}
		if err := storage.DeleteObject(ctx, object.Key); err != nil {
			return err
		}
	}
	return nil
}

func (s *Service) put(ctx context.Context, userID uint32, name string, content io.Reader, size int64, contentType string) (*File, error) {
	if err := validateName(name); err != nil {
		return nil, err
	}
	storage, err := s.resolve(ctx, userID)
	if err != nil {
		return nil, err
	}
	key := fmt.Sprintf("%s%s-%s", userPrefix(userID), uuid.NewString(), filepath.Base(name))
	object, err := storage.PutObject(ctx, key, content, size, infra.PutOptions{ContentType: contentType})
	if err != nil {
		return nil, err
	}
	if err := validateUserKey(userID, object.Key); err != nil {
		return nil, fmt.Errorf("storage returned invalid object key: %w", err)
	}
	url, err := storage.PresignedGetURL(ctx, key, defaultPresignedURLTTL)
	if err != nil {
		return nil, err
	}
	return &File{Key: object.Key, FileName: name, Size: object.Size, ContentType: contentType, ModifiedAt: object.LastModified, URL: url}, nil
}

func (s *Service) resolve(ctx context.Context, userID uint32) (infra.Storage, error) {
	if userID == 0 {
		return nil, fmt.Errorf("invalid user ID")
	}
	if s == nil || s.resolver == nil {
		return nil, fmt.Errorf("storage is not configured")
	}
	return s.resolver.Resolve(ctx, userID)
}

func userPrefix(userID uint32) string { return fmt.Sprintf("users/%d/", userID) }

func validateName(name string) error {
	if strings.TrimSpace(name) == "" || name == "." || name == ".." || name != filepath.Base(name) || strings.ContainsAny(name, "\\/\x00\r\n") {
		return fmt.Errorf("invalid file name")
	}
	if len(name) > 255 {
		return fmt.Errorf("file name is too long")
	}
	for _, r := range name {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("invalid file name")
		}
	}
	return nil
}

func validateUserKey(userID uint32, key string) error {
	prefix := userPrefix(userID)
	if userID == 0 || !strings.HasPrefix(key, prefix) || strings.ContainsAny(key, "\\\x00\r\n") {
		return fmt.Errorf("object does not belong to user")
	}
	for _, part := range strings.Split(key[len(prefix):], "/") {
		if part == "" || part == "." || part == ".." {
			return fmt.Errorf("invalid object key")
		}
	}
	return nil
}
