services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring_shared
    command:
      - "--housekeeping_interval=5s"          # Собирать данные раз в N сек
      - "--docker_only=true"                   # Только Docker контейнеры
      - "--storage_duration=1m"                # Время хранения данных в локальном кэше cAdvisor

networks:
  monitoring_shared:
    name: monitoring_shared
    external: true
