services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring_shared
    command:
      - "--housekeeping_interval=5s"          # Собирать данные раз в N сек
      - "--docker_only=true"                   # Только Docker контейнеры
      - "--storage_duration=1m"                # Время хранения данных в локальном кэше cAdvisor

  prometheus:
    image: prom/prometheus:v2.55.1
#    image: prom/prometheus:v3.5.5
    container_name: airorc_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=1GB"
      - "--web.enable-lifecycle"
    networks:
      - monitoring_shared
      - app_internal
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  grafana:
    image: grafana/grafana:11.3.1
#    image: grafana/grafana:13.1-slim
    container_name: airorc_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_ROOT_URL=https://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=10s # Запрещаем обновлять графики чаще N сек
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring_shared
      - app_internal
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring_shared:
    name: monitoring_shared
    external: true
  app_internal:
    name: app_internal
    external: true
